### ISSUE TITLE
Inconsistencies between blog post and repository code

### ISSUE THREAD

**Issue by brandyscarney** [drewrygh/ionic-offline-demo#1]
In the blog post you are telling us to add some code that is already added, specifically the SqlStorage code here: https://github.com/drewrygh/ionic-offline-demo/blob/master/app/pages/home/home.ts#L8 and here: https://github.com/drewrygh/ionic-offline-demo/blob/master/app/pages/home/home.ts#L25-L33

Also, there is an import for `DetailPage` when it doesn't exist. Some typescript errors are popping up such as `storage`, `city`, `state` need to be defined on the class prior to use, timestamp is defined as a string but used in an operation, etc. :)

**Comment by brandyscarney** [comment]
There are some typescript errors still: 
![screen shot 2016-08-03 at 12 14 48 pm](https://cloud.githubusercontent.com/assets/6577830/17373010/5efdf6ba-5974-11e6-805a-b3063d26b089.png)

**Comment by jgw96** [comment]
opened this pr https://github.com/drewrygh/ionic-offline-demo/pull/2 to fix the typescript errors
